server:
  address: localhost
  port: 8080

spring:
  data:
    mongodb:
      host: 127.0.0.1
      port: 27017
      database: sdw

sdw:
  id-generator-mode: SHORT

mqtt:
  client-id: sensor-data-warehouse
  uri: tcp://127.0.0.1:1883
  topic: ehome/sensors
  notification:
    separator:
      inner-message-border: "#"
      key-value: ":"