server:
  address: localhost
  port: 8080

sdw:
  id-generator-mode: SHORT

mqtt:
  client-id: sensor-data-warehouse
  uri: tcp://192.168.1.100:1883
  topic: ehome/sensors
  notification:
    separator:
      inner-message-border: "#"
      key-value: ":"